config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users
  root 'pages#home'

  get 'dashboard' => "pages#dashboard"

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      can :read, :all
      can :manage, Book do |book|
        book.try(:user) == user
      end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged

	belongs_to :user
	has_many :sales
	has_attached_file :image
	has_attached_file :resource

	validates_attachment_content_type :image, 
	content_type:  /^image\/(png|gif|jpeg)/,
	message: "Only images allowed"

	validates_attachment_content_type :resource,
	content_type: ['application/pdf'],
	message: "Only pdfs allowed"

	validates :image, attachment_presence: true
	validates :resource, attachment_presence: true

	validates_numericality_of :price,
	greater_than: 49, message: "must be at least 50 cents"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	before_create :populate_guid
	belongs_to :book

	include AASM


	aasm column: 'state' do
		state :pending, initial: true
		state :processing
		state :finished
		state :errored

		event :process, after: :charge_card do
			transitions from: :pending, to: :processing
		end

		event :finish do
			transitions from: :processing, to: :finished
		end

		event :fail do 
			transitions from: :processing, to: :errored
		end
	end

	def charge_card
		begin
			save!
			charge = Stripe::Charge.create(
				amount: self.amount,
				currency: "usd",
				card: self.stripe_token,
				description: "Book Sale"
				)
			self.update(stripe_id: charge.id)
			self.finish!
		rescue Stripe::StripeError => e
			self.update_attributes(error: e.message)
			self.fail!
		end
	end

	private

	def populate_guid
		self.guid = SecureRandom.uuid()
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_path, notice: "You are not authorized to access this area"
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @books = Book.where(availability: true)
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
    authorize! :manage, @book
  end

  def create
    @book = current_user.books.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    authorize! :manage, @book
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    authorize! :manage, @book
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]
  def home
  	if current_user
  		redirect_to books_path
  	end
  	@books = Book.first(4)
  end

  def dashboard
  	@books = current_user.books
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	def create
		book = Book.find_by!(slug: params[:slug])
		sale = book.sales.create(
			amount: book.price,
			buyer_email: current_user.email,
			seller_email: book.user.email,
			stripe_token: params[:stripeToken])
		sale.process!
		if sale.finished?
			redirect_to pickup_url(guid: sale.guid), notice: "Transaction Successful"
		else
			redirect_to book_path(book), notice: "Something went wrong"
		end
	end

	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@book = @sale.book
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">
<div class="thumbnail">
<%= link_to book_path(book) do %>
<%= image_tag book.image.url(:original), class: "img-responsive" %>
<% end %>

<div class="caption">
<p><strong><%= link_to book.name, book_path(book) %></strong></p>
<p>$<%= book.price.to_f / 100 %></p>
</div>
</div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :name, required: true, label: false, placeholder: "Name", input_html: {class: "form-control"} %>
    <%= f.input :author, required: true, label: false, placeholder: "Author's name", input_html: {class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "Description", input_html: {class: "form-control", rows: 5} %>
    <br>
    <%= f.input :price, required: true, label: false, placeholder: "Price", input_html: {class: "form-control"} %>
    <%= f.input :image %>
    <%= f.input :resource %>
    <div class="checkbox text-center">
    <p>Availability</p>
    <%= f.input :availability, required: false, label: false %>
    </div>
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
<h1 class="text-center">Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">

<%= render @books %>

</div>
</div>

app/views/books/new.html.erb
<div class="container">
<h1 class="text-center">New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-6">
<%= image_tag @book.image.url(:original), class: "img-responsive" %>
</div>
<div class="col-md-6">
<h3><%= @book.name %> by <%= @book.author %></h3>
<p class="justify"><%= @book.description %></p>
<h4 class="text-right">$<%= @book.price.to_f / 100 %></h4>

<% if current_user %>
<%= form_tag buy_path(slug: @book.slug) do %>
<script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-amount="<%= @book.price %>"
    data-name="eStuk"
    data-description="<%= @book.name %>"
    data-email="<%= current_user.email %>">
  </script>
<% end %>
<% else %>
<p>Please Login First to Buy</p>
<% end %>
</div>
</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %><i class="fa fa-book"></i> eStuk <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Books", books_path %></li>
      <% if current_user %>
      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estuk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>

<% flash.each do |type, message| %>
<div class="alert alert-info fade-in">
<button class="close" data-dismiss="alert">x</button>
<%= message %>
</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/_books.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Available</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.id %></td>
          <td><%= link_to book.name, book_path(book) %></td>
          <td><%= book.availability %></td>
          <td><%= link_to "Edit", edit_book_path(book) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/pages/_purchased.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
      <% @purchased.each do |sale| %>
        <tr>
          <td><%= link_to sale.book.name, pickup_path(sale.guid) %></td>
          <td><%= time_ago_in_words(sale.created_at) %> ago</td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/pages/_sales.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Buyer</th>
        </tr>
      </thead>
      <tbody>
      <% @sales.each do |sale| %>
        <tr>
          <td><%= link_to sale.book.name, pickup_path(sale.guid) %></td>
          <td><%= time_ago_in_words(sale.created_at) %> ago</td>
          <td><%= sale.buyer_email %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/pages/dashboard.html.erb
<div class="container">
<div class="row">
<h1 class="text-center">Dashboard</h1>
<div class="text-center"><%= link_to "New Book", new_book_path, class: "btn btn-primary btn-sm" %></div>
<div class="clearfix"></div>
<div class="col-md-4">
<div class="dash-box">
<h4 class="white uppercase">
Books
</h3>
</div>
<%= render "books" %>
</div>
<div class="col-md-4">
<div class="dash-box">
<h4 class="white uppercase">
Purchased
</h3>
</div>
<%= render "purchased" %>
</div>
<div class="col-md-4">
<div class="dash-box">
<h4 class="white uppercase">
Sales
</h3>
</div>
<%= render "sales" %>
</div>
</div>
</div>

app/views/pages/home.html.erb
<div class="background-image">
<div class="container">
<div class="col-lg-6 col-lg-offset-3">
<div class="jumbotron text-center">
<h2 class="uppercase">Welcome to our store</h2>
<p>The largest online Digital Books Store</p>
<%= link_to "Books", books_path, class: "btn btn-primary btn-block" %>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-block" %>
</div>


</div>
<div class="clearfix"></div>
<div class="row">
<%= render @books %>




</div>
</div>
</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
<h1>Congratulations on your order <%= @sale.guid %></h1>
<p>Here is your download link:</p>
<%= link_to "Download", @book.resource.url %>
</div>